name: Delete

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 2 * *'

jobs:
  delete-packages:
    runs-on: ubuntu-latest
    steps:

      - name: Delete Out of Date Packages
        uses: actions/delete-package-versions@v5
        with:
          package-name: 'cloudflare-ddns'
          package-type: 'container'
          min-versions-to-keep: 3
